M48
; DRILL file {KiCad 9.0.3} date 2025-11-18T20:02:21+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-18T20:02:21+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0701
%
G90
G05
T1
X8.6902Y-2.2677
T2
X7.2102Y-2.773
X7.2102Y-3.373
X8.8102Y-2.773
X8.8102Y-3.373
M30
